server:
  port: 8001


spring:
  application:
    #服务注册的名称
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/payment?serverTimezone=GMT&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
  banner:
    image:
      location: classpath:banner.jpg

mybatis:
  mapperLocations: classpath:mapper/*.xml
  #设置别名用于mapper中传递参数不用写全类名
  type-aliases-package: com.yff.springcloud.entity

eureka:
  client:
    #将自己注册进EurekaServer
    register-with-eureka: true
    #从Eureka抓取自己有的注册信息，单节点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      #defaultZone: http://eureka7001.com:7001/eureka/
      #注册到eureka server集群中
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    #修改服务名称
    instance-id: payment8001
    #显示ip
    prefer-ip-address: true
    #Eureka客户端想服务端发送心跳的时间间隔，单位秒（默认30秒）
    #lease-renewal-interval-in-seconds: 1
    #Eureka服务端在收到最后一次心跳后等待时间上限，单位秒（默认90秒），超时将剔除服务
    #lease-expiration-duration-in-seconds: 1