server:
  port: 9527
spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能，利用微服务名进行路由
      routes:
        - id: payment_routh #路由的ID，没有固定规则但要求唯一，建议配合服务名
          #uri: http://localhost:8001   #匹配后提供服务的路由地址
          uri: lb://CLOUD-PAYMENT-SERVICE
          predicates:
            #- Path=/payment/**   #断言,路径相匹配的进行路由
            - Path=/payment/lb/**   #断言,路径相匹配的进行路由
            #- After=2021-09-16T14:57:15.474+08:00[Asia/Shanghai] #在这个时间之后才可访问路由
            #- Cookie=username,yff #必须带cookie才可访问路由
            #- Header=X-Request-Id, \d+ #请求头
            #- Method=GET
          filters:
            - AddRequestParameter=aa, zhangsan #向request中添加参数aa=zhangsan
eureka:
  instance:
    hostname: cloud-gateway-service
  client:
    service-url:
      register-with-eureka: true
      fetch-registry: true
      defaultZone: http://eureka7001.com:7001/eureka